name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
    - name: Build
      run: dotnet build "C:\Users\user\source\repos\TestCICD\src\TestCICD.Web\TestCICD.Web\TestCICD.Web.csproj" --configuration Release
      working-directory: C:\Users\user\source\repos\TestCICD\src\TestCICD.Web\TestCICD.Web

    - name: Test
      run: dotnet test --no-build
      working-directory: C:\Users\user\source\repos\TestCICD\src\TestCICD.Web\TestCICD.Web